version: '3.6'

services:
  hotspot_web:
    container_name: hotspot_web
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./www:/app
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - hotspot_php
  hotspot_php:
    container_name: hotspot_php
    build:
      context: ./config/php-fpm
    expose:
      - 9000
    volumes:
      - ./www:/app
    depends_on:
      - hotspot_db
  hotspot_db:
    container_name: hotspot_db
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=data
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data: