version: '3.6'

services:
  hotspot_web:
    container_name: hotspot_web
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./www:/app
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
  hotspot_php:
    container_name: hotspot_php
    build:
      context: ./config/php-fpm
    expose:
      - 9000
    volumes:
      - ./www:/app
  hotspot_db:
    container_name: hotspot_db
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=data
    ports:
      - "127.0.0.1:3306:3306"
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql
      - ./config/db-seed.sql:/docker-entrypoint-initdb.d/db-seed.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql

volumes:
  data: